DROP INDEX PERSON_FIRST_NAME_IX;
DROP INDEX PERSON_LAST_NAME_IX;

DROP TABLE "ROLE";
DROP TABLE GROUP_MEMBER;
DROP TABLE "GROUP";
DROP TABLE PERSON;
DROP TABLE "USER";
DROP TABLE INVITATION;
DROP TABLE TENANT;

DROP SEQUENCE ROLE_SQ;
DROP SEQUENCE GROUP_SQ;
DROP SEQUENCE USER_SQ;
DROP SEQUENCE INVITATION_SQ;
DROP SEQUENCE TENANT_SQ;